// Remove Palindromic Subsequences

/*
 Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
Return the minimum number of steps to make the given string empty.
A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.
A string is called palindrome if is one that reads the same backward as well as forward.
*/

import java.util.*;
class Main{
public static int removePalindromeSub(String s) {
      
        char[] c=new char[s.length()];
        ArrayList<Character> al=new ArrayList<>();
        ArrayList<Character> bl=new ArrayList<>();
         
        for(int i=0;i<s.length();i++)
        {
            char a=s.charAt(i);
            al.add(a);
            bl.add(a);
            
        }
       
        Collections.reverse(bl);
        
        if(al.size()==0)
	{
            return 0;
	}
        
        else if(al.equals(bl))
        	{
           return 1;
        	}
        else
	{
            return 2;
	}         
}

	public static void main(String args[])
		{
			Scanner sc=new Scanner(System.in);
			System.out.println("Enter the string: ");
			int ans=0;
			String s=sc.next();
			ans=removePalindromeSub(s);
			System.out.println("Output: "+ans);

		}
	}